root = "."
tmp_dir = ".air"

[build]
bin = "./.air/slash.exe --mode dev"
cmd = "go build -o ./.air/slash.exe ./bin/slash/main.go"
delay = 1000
exclude_dir = [".air", "frontend", "build"]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
full_bin = ""
send_interrupt = true
kill_delay = 2000
